---
- name: Deploy a jar file
  hosts: all
  remote_user: root
  tasks:
    - name: Installing java8 package
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Copy jar file to home directory
      copy:
        src: ./target/CalculatorDevops-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/
        mode: '0755'
